services:
  notification:
      build:
        context: .
        dockerfile: ./services/notification/Dockerfile
        target: dev
      volumes:
        - ./:/moneymate-backend
        - ./shared:/moneymate-backend/shared
        - ./services/notification/migrations:/app/migrations
      working_dir: /moneymate-backend/services/notification
      env_file:
        - .env
      environment:
        - CONFIG_PATH=/moneymate-backend/services/notification/config/config.yaml
        - POSTGRES_HOST=${POSTGRES_HOST}
        - POSTGRES_PORT=5432
        - ENVIRONMENT=dev
        - FIREBASE_PROJECT_ID=money-mate2026
        - FIREBASE_CREDENTIALS_PATH=/moneymate-backend/firebase-service-account.json
      ports:
        - "9095:9095"
      restart: unless-stopped
      depends_on:
        postgres:
          condition: service_healthy
        redis:
          condition: service_healthy
      networks:
        - moneymate-network
  merchant:
    build:
      context: .
      dockerfile: ./services/merchant/Dockerfile
      target: dev
    volumes:
      - ./:/moneymate-backend
      - ./shared:/moneymate-backend/shared
    working_dir: /moneymate-backend/services/merchant
    env_file:
      - .env
    environment:
      - CONFIG_PATH=/moneymate-backend/services/merchant/config/config.yaml
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=5432
      - ENVIRONMENT=dev
    expose:
      - "50053"
      - "9092"
    ports:
      - "50053:50053"
      - "9092:9092"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - moneymate-network

  support:
    build:
      context: .
      dockerfile: ./services/support/Dockerfile
      target: dev
    volumes:
      - ./:/moneymate-backend
      - ./shared:/moneymate-backend/shared
    working_dir: /moneymate-backend/services/support
    env_file:
      - .env
    environment:
      - CONFIG_PATH=/moneymate-backend/services/support/config/config.yaml
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=5432
      - ENVIRONMENT=dev
      - REDIS_ADDR=redis:6379
    ports:
      - "8085:8085"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - moneymate-network

  payment:
    build:
      context: .
      dockerfile: ./services/payment/Dockerfile
      target: dev
    volumes:
      - ./:/moneymate-backend
      - ./shared:/moneymate-backend/shared
      - ./services/payment/migrations:/app/migrations
    working_dir: /moneymate-backend/services/payment
    env_file:
      - .env
    environment:
      - CONFIG_PATH=/moneymate-backend/services/payment/config/config.yaml
      - AUTH_SERVICE_URL=http://auth:8081
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=5432
      - ENVIRONMENT=dev
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
    ports:
      - "9094:9094"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - moneymate-network

  rewards:
    build:
      context: .
      dockerfile: ./services/rewards/Dockerfile
      target: dev
    volumes:
      - ./:/moneymate-backend
      - ./shared:/moneymate-backend/shared
      - ./services/rewards/migrations:/app/migrations
    working_dir: /moneymate-backend/services/rewards
    env_file:
      - .env
    environment:
      - CONFIG_PATH=/moneymate-backend/services/rewards/config/config.yaml
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_SSL=disable
      - ENVIRONMENT=dev
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - REWARDS_DB_USER=${REWARDS_DB_USER}
      - REWARDS_DB_PASSWORD=${REWARDS_DB_PASSWORD}
      - REWARDS_PAYMENT_SERVICE_URL=http://payment:9094
      - KAFKA_CA_CERT_PATH=/moneymate-backend/shared/certs/aiven-ca.pem
    ports:
      - "9096:9096"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - moneymate-network

  gateway:
    build:
      context: .
      dockerfile: ./services/gateway/Dockerfile
      target: dev
    volumes:
      - ./:/moneymate-backend
      - ./shared:/moneymate-backend/shared
    working_dir: /moneymate-backend/services/gateway
    env_file:
      - .env
    environment:
      - CONFIG_PATH=/moneymate-backend/services/gateway/config/config.yaml
      - SERVER_PORT=8080
      - SERVICES_AUTH_ADDR=auth:8081
      - SERVICES_MERCH_ADDR=merchant:9092
      - SERVICES_PAYMENT_ADDR=payment:9094
      - SERVICES_SUPPORT_ADDR=support:8085
      - SERVICES_REWARDS_ADDR=rewards:9096
      - REDIS_ADDRESS=redis:6379


    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      auth:
        condition: service_started
    networks:
      - moneymate-network

  auth:
    build:
      context: .
      dockerfile: ./services/auth/Dockerfile
      target: dev
    volumes:
      - ./:/moneymate-backend
      - ./shared:/moneymate-backend/shared
      - ./services/auth/migrations:/app/migrations
    working_dir: /moneymate-backend/services/auth
    env_file:
      - .env
    environment:
      - CONFIG_PATH=/moneymate-backend/services/auth/config/config.yaml
      - PAYMENT_SERVICE_URL=http://payment:9094
      - POSTGRES_USER=${AUTH_DB_USER}
      - POSTGRES_PASSWORD=${AUTH_DB_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${AUTH_DB_USER}
      - POSTGRES_PASSWORD=${AUTH_DB_PASSWORD}
      - REDIS_ADDR=redis:6379
      - ENVIRONMENT=${ENVIRONMENT}
    expose:
      - "8081"
    ports: ["8081:8081"]  
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - moneymate-network

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/postgres:/docker-entrypoint-initdb.d
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./infra/postgres/roles:/docker-entrypoint-initdb.d/roles
    networks:
      - moneymate-network

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - moneymate-network

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@moneymate.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:                     
      - moneymate-network

volumes:
  postgres_data:
  redis_data:

networks:
  moneymate-network:
    driver: bridge
